//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CBOPortalEntities : DbContext
    {
        public CBOPortalEntities()
            : base("name=CBOPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlertDetails> AlertDetails { get; set; }
        public virtual DbSet<CBOUpdatesDetails> CBOUpdatesDetails { get; set; }
        public virtual DbSet<NewWinsDetails> NewWinsDetails { get; set; }
        public virtual DbSet<PipelineDetails> PipelineDetails { get; set; }
        public virtual DbSet<SpotLightDetails> SpotLightDetails { get; set; }
        public virtual DbSet<EventDetails> EventDetails { get; set; }
    }
}
