//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipelineDetails
    {
        public int ID { get; set; }
        public string CategoryCode { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public System.DateTime ExpectedStartDate { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsMobileDisplay { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
